name: Terraform + Deploy Website

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    outputs:
      ec2_ip: ${{ steps.capture.outputs.ec2_ip }}
      private_key: ${{ steps.capture.outputs.private_key }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init & Apply
        working-directory: infrastructure/environment/dev
        run: |
          terraform init
          terraform apply -auto-approve

      - id: capture
        name: Capture Terraform Outputs
        working-directory: infrastructure/environment/dev
        run: |
          echo "ec2_ip=$(terraform output -raw instance_public_ip)" >> $GITHUB_OUTPUT
          echo "private_key=$(terraform output -raw private_key_pem)" >> $GITHUB_OUTPUT

  deploy:
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          # Write private key, remove CRLF if copied from Windows
          echo "${{ needs.terraform.outputs.private_key }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Wait for EC2 SSH
        run: |
          for i in {1..30}; do
            if nc -zv ${{ needs.terraform.outputs.ec2_ip }} 22; then
              echo "SSH is ready"
              break
            fi
            sleep 10
          done

      - name: Copy app & Deploy
        run: |
          HOST=${{ needs.terraform.outputs.ec2_ip }}
          USER=ec2-user

          ssh -o StrictHostKeyChecking=no $USER@$HOST "mkdir -p ~/app"
          scp -o StrictHostKeyChecking=no -r deploy.sh deploy_app.sh index.html style.css script.js $USER@$HOST:~/app/
          ssh -o StrictHostKeyChecking=no $USER@$HOST "chmod +x ~/app/*.sh && ~/app/deploy_app.sh"
