name: Terraform + Deploy + Antigravity

on:
  push:
    branches:
      - main
jobs:
  terraform:
    runs-on: Red Hat Enterprise Linux 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: C:\Terraform\Terraform_aws
        run: terraform init

      - name: Terraform Validate
        working-directory: C:\Terraform\Terraform_aws
        run: terraform validate

      - name: Terraform Plan
        working-directory: C:\Terraform\Terraform_aws
        run: terraform plan

      - name: Terraform Apply
        working-directory: C:\Terraform\Terraform_aws
        run: terraform apply -auto-approve
